---
author:
- On behalf of all the authors, Dr. Alain Danet
opening: Dear Editors,
closing: Sincerely yours,
fontsize: 11pt
return-address:
- Dr. Alain Danet
- School of Biosciences
- University of Sheffield, Western Bank
- S10 2TN, Sheffield, UK
output:
  linl::linl:
    keep_tex: true

#letterhead: misc/letterhead.pdf
signature: /home/alain/Documents/Administration/signature.pdf
---

```{r, results = "hide", include = FALSE}
Sys.setlocale("LC_TIME", "C")
```

Please find enclosed our manuscript entitled "Species diversity promotes
facilitation under stressful conditions", which we submit for consideration in
Oikos special issue "The role of plant facilitation in mediating climate change
impact on biodiversity".

In the midst of current climate change, it is now more important than
ever to understand the role of climate change on biodiversity in order to
design and implement adapted conservation policies. This is particularly true in
drylands, which are expected to suffer from more frequent and severe droughts in
the coming decades. Yet, dryland vegetation is characterized by its patchy
structure which is generated by positive interactions provided by nurse
plants to other plants ("beneficiary" plants). Nurse plants could mitigate the
effects of climate change on dryland biodiversity, but the effects of positive
interactions in species diverse beneficiary communities have been overlooked.
It is a critical gap to lift because the effects of nurse plants can be
modulated by interactions among beneficiary plants.

We addressed this challenging task by investigating the effects of increasing
species richness of beneficiary communities on nurse net effects on the survival
and biomass of beneficiary communities. We set up an experiment
in Mediterranean semi-arid steppeland where we transplanted sapling beneficiary
communities of 1 (monoculture) or 3 (mixture) species either under a nurse or in
open sites. We further tested how water stress alleviation modulated the effects
of the nurse on beneficiary communities. We found facilitation between nurse and
beneficiary communities only in mixture and no watered conditions. We also found
that stress alleviation - either by a nurse in no watered conditions or watered
conditions in open sites - both increased complementarity effects on biomass
(i.e. species had higher biomass in mixture than expected from monoculture).
Furthermore, stress alleviation led to same change in beneficiary functional
trait, toward a less stress tolerant strategy. However, we found a difference
between stress alleviation provided by watering and nurse on selection effects,
nurse generating quasi neutral selection effects regardless of the water stress
(it was not the case for watering).

Our study provides an original perspective on the effects of facilitation in
species diverse communities, but also a better understanding of the
mechanisms of facilitation in stressful environments. Our results are coherent
with the abundant literature reporting stress dependant nurse effects on
beneficiary communities but highlights that species rich beneficiary communities
experienced the strongest facilitative effects. Our results are also coherent
with Biodiversity-Ecosystem Functioning literature, showing that facilitation by
nurse plants can increase complementarity effects in beneficiary communities.
Overall this study highlights at the same time the potential of nurse plants to
maintain biodiversity in climate change but also the potential critical
consequences of nurse losses if they were to be severely impacted by climate
change.

As Oikos has been at the forefront of the research on plant facilitation, we are
confident that our study will interest the broad readership of the journal and
will stimulate exciting new perspectives and research on facilitation
consequences in species rich communities. We think that the methods used to
asses the net effects of nurse plants on biomass and survival, but also
complementarity and selection effects will be of interest for a large
readership. Lastly, this study of high interest for agro-ecologists and
conservation practitioners as we provide the fist assessment on how nurse plant
effects are modulated by the species richness of beneficiary communities. The
enclosed manuscript has been edited and approved by all the authors and has not
been published or submitted to any other journal.
