---
title: "Species diversity promotes facilitation under stressful conditions"
author: "Alain Danet, Susana Bautista, Alexandre Génin, Andrew P. Beckerman, Fabien Anthelme, Sonia Kéfi"
date: ""
output:
  bookdown::pdf_document2:
    latex_engine: xelatex
    keep_tex: true
    spacing: double
    number_sections: false
bibliography: "bibliography.bib"
#csl: "nature.csl"
link-citations: true
toc: false
linestretch: 2.0
header-includes:
  - \usepackage{lineno}
  - \linenumbers
---

# Author affiliations:

- Alain Danet:
  - ISEM, CNRS, Univ. Montpellier, IRD, EPHE, Montpellier, France
  - Laboratory AMAP, IRD, University of Montpellier, CIRAD, CNRS,
  INRA, Montpellier, France
  - Current address: School of Biosciences, University of Sheffield, S10 2TN, Sheffield, UK
- Susana Bautista: Department of Ecology and IMEM, University of Alicante,
  Alicante, Spain
- Alexandre Génin:
  - Estación Costera de Investigaciones Marinas, Las Cruces, Departamento de
    Ecología, Pontificia Universidad Católica de Chile, Santiago 8331150, Chile
  - Copernicus Institute of Sustainable Development, Utrecht University, PO Box
    80115, 3508 TC Utrecht, The Netherlands
- Andrew P. Beckerman: School of Biosciences, Ecology and Evolutionary Biology, University of Sheffield, Western Bank, S10 2TN, Sheffield, UK
- Fabien Anthelme: Laboratory AMAP, IRD, University of Montpellier, CIRAD, CNRS,
  INRA, Montpellier, France
- Sonia Kéfi:
  - ISEM, CNRS, Univ. Montpellier, IRD, EPHE, Montpellier, France
  - Santa Fe Institute, Santa Fe, New Mexico 87501

# Corresponding author

Alain Danet: a.h.danet@sheffield.ac.uk
